[package]
name = "duel-game-core"
version = "0.1.0"
description = "Generic 2-player global-board session engine"
files = [ "src/**/*.mo" ]

[dependencies]
core = "2.6.1"
ic-websocket-cdk = "./src/ic-websocket-cdk/src"
# ic-websocket-cdk dependencies
ic-certification = "1.1.0"
sha2 = "0.2.5"
cbor = "4.1.0"

[optimize]

[toolchain]
moc = "1.11.2"
pocket-ic = "15.0.0"
wasm-opt = "132"

[dev-dependencies]
bench-helper = "0.0.3"
